### ISSUE TITLE
The file is not runnable issue

### ISSUE THREAD

**Issue by Zack-Tay** [nus-cs2103-AY2324S2/forum#153]
<img width="136" alt="ui" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101039486/dd4070ba-3c93-4f64-bfa2-7a8339d51a0e">
<img width="707" alt="uiafter" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101039486/2cfed2f0-a58c-4022-bc58-227d7f2749a0">
<img width="721" alt="uirun" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101039486/c66305e9-5d1e-4df4-8088-5457299d8238">
<img width="664" alt="module" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/101039486/70c00153-3e56-4551-991e-8132048cc4da">

Hi all, I'm sure this is not the expected behaviour but everytime I load gradle project (see 3rd pic), the run icon goes from green to grey (in other words, my file goes from being able to run to "the file in the editor is not runnable"). There is no quick fix other than me having to manually remove the modules and adding them back and reconfiguring the source folders. I am pretty sure this is not the expected behaviour, am I doing something wrong?
Would love to hear some suggestions on how to fix this ASAP. Thanks in advance.

**Comment by E0735389** [comment]
As far as I can see there is not enough information to diagnose the issue. What does the red squiggle lines/error messages say and can you fix them first?

**Comment by damithc** [comment]
@Zack-Tay Perhaps you can push the latest code to you fork (or a branch of it) and give the link here so that others can try to replicate it?
It is also useful to know the steps that lead you to encounter this problem. That is, what thing you did caused you to go from not-having-this-problem to having-this-problem?

**Comment by Zack-Tay** [comment]
Hi everyone and prof @damithc, I have added a new branch "branch-Issue" with my latest code in it. https://github.com/Zack-Tay/ip/tree/branch-Issue

Not sure what went wrong as well, after merging the add-gardle-support, I kept getting episodes of "the file in the editor is not runnable". The problem is persistent because 
"the run icon goes from green to grey (in other words, my file goes from being able to run to "the file in the editor is not runnable"). There is no quick fix other than me having to manually remove the modules and adding them back and reconfiguring the source folders. "

and after I click "load gardle scripts" (3rd pic) or do any updates to the build gradle file, the problem that i have quoted will occur again.

Thanks in advance for anyone helping!

**Comment by YuSoonZ** [comment]
I think the issue could be in your load file program, or something that caused it to malfunction.
If you had just updated your class/change names etc, you can consider to delete the previous file that was created and for it to create a whole new one on its own again. That should fix it for your next iterations with the updated file. (Was what i do when i had some loading issues and discovered it was due to change of class/name)

**Comment by adammangzijun** [comment]
@Zack-Tay 
Maybe you can look through your gradle set up again, see if you missed up any configurations?

**Comment by lhy-hoyin** [comment]
Hello @Zack-Tay, I am a senior from a previous batch, dropping by to see if I can help out.

I see that you have changed the  folder directory from `src/main/java/...` to `src/main/Fredricksen/...`. Perhaps try changing to such that `src/main/java/...` is still there? (It can be like `src/main/java/Fredricksen/...`). 
Don't forget to update your `import`s as well as your `build.gradle` (if needed) too.

There are some benefits to keeping the convention, as mentioned in [What is the advantage of the 'src/main/java'' convention?](https://stackoverflow.com/questions/3004710/what-is-the-advantage-of-the-src-main-java-convention).

Do try out the solution and let us know if it worked for you. If the issue is still not resolved, do update here with more infomation.

---

I download your code from your `branch-Issue` branch to try and test it. However, I wasn't able to replicate the error exactly as you have described. I made the fix as I have described above and it seems to be able to build and run.

**Comment by damithc** [comment]
> I see that you have changed the folder directory from `src/main/java/...` to `src/main/Fredricksen/...`. Perhaps try changing to such that `src/main/java/...` is still there?

Yup, for Gradle to work, certain things should be where Gradle expects them to be. And Gradle expects the source code to be in `src/main/java` folder.

**Comment by Zack-Tay** [comment]
Thanks for all the inputs Prof @damithc and @adammangzijun, @lhy-hoyin, @E0735389, @YuSoonZ, I might have accidentally changed the name of the src/main/java to src/main/Fredricksen folder instead of adding to it in this manner src/main/java/Fredricksen. Thanks for the help. Will close the issue.
